version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_clinica
    ports:
      - "5434:5432"                    # Puerto host 5434 → contenedor 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:                      # ← garantiza que la BD esté “up”
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile  
    image: clinica-api:1.0.0
    container_name: clinica_api
    ports:
      - "9009:3001"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
      JWT_SECRET: ${JWT_SECRET}
      PORT: "3001"
    depends_on:
      postgres:
        condition: service_healthy    # ← espera hasta que el health-check sea OK
    command: >
      sh -c "npx prisma db push --accept-data-loss &&
            node dist/main.js"

    restart: always

volumes:
  postgres_data: 
    driver: local
